name: "Nemo"
description: "File Manager"
icon: "󰝰"
command: "nemo & sleep 5"
context:
  - name: "Open Home folder"
    command: "nemo ~ & sleep 5"
  - name: "Open Root folder"
    command: "nemo / & sleep 5"
  - name: "Open Documents folder"
    command: "nemo ~/Documents & sleep 5"
