{
  ...
}:

{

  imports = [
    ./aerc.nix
    ./atuin.nix
    ./bat.nix
    ./bottom.nix
    ./carapace.nix
    ./catppuccin.nix
    ./cava.nix
    ./cursor.nix
    ./default_apps.nix
    ./direnv.nix
    ./drawy.nix
    ./fonts.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./gtk.nix
    ./haal.nix
    ./helix.nix
    ./hyprlock.nix
    ./hyprpolkitagent.nix
    ./keepassxc.nix
    ./lazygit.nix
    ./mangohud.nix
    ./niri.nix
    ./nushell.nix
    ./qt.nix
    ./rsstig.nix
    ./scripts.nix
    ./spyglass.nix
    ./starship.nix
    ./swaync.nix
    ./swayosd.nix
    ./tmux.nix
    ./waybar.nix
    ./xdg_autostart.nix
    ./yazi.nix
    ./ytsurf.nix
    ./zathura.nix
    ./zoxide.nix
  ];

}
