[[language]]
name = "markdown"
language-servers = [ "uwu-colors", "markdown-oxide" ]

[language-server.uwu-colors]
command = "uwu_colors"

[language-server.markdown-oxide]
command = "markdown-oxide"

[language.soft-wrap]
enable            = true
max-wrap          = 25
max-indent-retain = 40
wrap-indicator    = "󰘍 "
